join先カラムの検索追加。
yuroyoro/administa pull request #1
Opened 2016-10-25 10:16 UTC by vikke

* 一覧のjoin先カラムを検索対象に追加。
* ダイアログ表示位置調整。
* PK検索のバグ修正。

2016-10-26 03:33 UTC, yuroyoro requested changes

2016-10-26 03:33 UTC, yuroyoro commented on js/components/PropertyMixin.js
> +    if (name == 'dmp_section') {
あんまりwo独自のコードをいれてほしくないです

2016-10-26 03:33 UTC, yuroyoro commented on lib/administa/config/menu.rb
> +          #binding.pry if controller == :dmp_section_key
こういうの消してほしいです

2016-10-26 03:33 UTC, yuroyoro commented on lib/administa/model/relation.rb
> +        puts to_sql
消してください

2016-10-26 03:33 UTC, yuroyoro commented on lib/administa/model/relation.rb
> +        query = klass.arel_table[:id].eq(keyword.to_i) if keyword =~ /^\d+$/
検索ワードが数字のみの場合は、idのみ検索対象にするという仕様に変更ですか?

ワードが"99" の場合、 id:99 のレコードと、 "test99" とか"foo999"とかもhitするような意図だったんですが

2016-10-26 03:33 UTC, yuroyoro commented on js/components/PropertyMixin.js
> +// vim:set expandtab ts=2 sw=2 sts=2 tw=0:
けしてください

2016-10-26 03:33 UTC, yuroyoro commented on lib/administa/model/relation.rb
> +      def to_sql(rel = nil)
デバッグ目的ですか? だったらここに書かないで欲しいです

2016-10-26 03:33 UTC, yuroyoro commented on js/AppDispatcher.js
> +// vim:set expandtab ts=2 sw=2 sts=2 tw=0:
エディタ固有の設定はいれないでほしいです

2016-10-26 06:56 UTC, vikke commented on js/components/PropertyMixin.js
> +    if (name == 'dmp_section') {
debug code削除漏れです。修正しました。

2016-10-26 06:56 UTC, vikke commented on js/components/PropertyMixin.js
> +// vim:set expandtab ts=2 sw=2 sts=2 tw=0:
消しました。

2016-10-26 06:56 UTC, vikke commented on lib/administa/config/menu.rb
> +          #binding.pry if controller == :dmp_section_key
すいません。消し漏れです。修正しました。

2016-10-26 06:57 UTC, vikke commented on lib/administa/model/relation.rb
> +        puts to_sql
消しました。

2016-10-26 06:57 UTC, vikke commented on lib/administa/model/relation.rb
> +      def to_sql(rel = nil)
消しました。

2016-10-26 07:49 UTC, vikke commented on lib/administa/model/relation.rb
> +        query = klass.arel_table[:id].eq(keyword.to_i) if keyword =~ /^\d+$/
意図を汲み取れてなかったです。修正しました。

2016-10-26 07:50 UTC, vikke commented
review内容修正しました。再レビューお願いします。

2016-10-28 09:52 UTC, yuroyoro approved these changes

2016-10-28 10:44 UTC, merged